sudo: required

services:
  - docker

language: node_js

node_js:
  - '8.9'

env:
  global:
    - secure: VpEoTSgJNI/try81g9ATgktdV6dGaIGgfmOoytYWukSZGNzscpy1ttvj064HYSKiWLhkfiSC0m0K2DBGlL1HN4peFqhdd2oXwSTrLFc2eTWlmmO3Gm6eobD+UXjCthtqIcGcVa7hYDQYJXYMYKOOdjQ0Sgg+KxGK9FuOPDterC/maQkVZMfC8IB4TN+CQuYoxApCwvPRZzNzZgwzZ5pc5XTsMRtLK3qRSF/wqOmuVPH6sbylHiP7M/C340rsNie4rS+9qwVz6o8GqbiyZ89XBxd6SUAV7U7lC2A4DI7k0faoECx23kqRpmLixbyhc//96Y4zeSBu89X6+wllaCbZH2iLH+3mLaXa+fsGR9W8y4l5kCDSQ4enWw5a2nWSSFfhO47DTNBXCbz8i2ORmjaDxLjYjHAyb91gojbAweUqedo2cf1iqtRHOPDDLJu9M80MjgDFJeC+fwOo/Qloti/qKOCbQmZjV0IiUomdqEjrU4uUaSH8Bh4VnLqDTQAB2Hsx1E45J2gdVHO9WDAzEhMYweBBdlPsEJ4b+1EaGYHXgA0VpQ3MfDKHHSuyeqhmTnKptMLXge9Z5dmzvgfVwexSdEmDUl2/+GWSUEpcrmrC5ziSvd7t/0MpxPVKJJ0cYPHDqtKodRJx5Okt6psNvO75Wogk+e7nW0ouRtDQaEbAuDg=
    - secure: UDs+EY93QDGu8xLMhDPcBy1Mj9l3DQWp8qy/sd69ft6hlu8/pYnxSovFJEh8ev96Pskmh2Y8y5nKAITxkXG0vZmb89Mln+P8ooDPL9GZSDW8VZx6egSPMqFjlxBpPHK5vWun8mk65bC+MN8TjECLnz0Olh5fZDn7QG5+2yFMIFyFmPUVj/WRT34KSPl644kyrJMW2X4iAK/fHj5DhoaC89GxExNBugk60PdO7zSjOo2MiQs6daLHphNhLfjqNf8zhRXsJKRGg8avxJaICP9/5L6vWkeZ63nWB3CqxuImiH9blqt/M/WsfqjY0OSaQEM12yj1z2kcOMinZmJEjOdmeNUfc0O0osn3V1O6b69pciZwVZrfpmSE6Jd0RfKZd0z67GuQg7/l3Q1zoYreliPxS5YteuCJKYsrlqV7VrIMUaqiA81iUWnlOlsYjSnz3FfrpAfavcc82ho9tCyKoPCXVE34K+8tr3JUMGz4GMo2KK/4olxn7CuNF5I1OEYC7fEIM69b6YGb90hAiaa5tN43Q+mzrTvzMNzZhA47GlC676uRm78iyd1LIFS+gnzKuQD/7FCpbN3BKbfuzXvX0VaL8Ba77XOni6vy8YrhBhA5/XAUTylU1tMloA6rrXdI0ji8pim7IIWKqDQHr5wTCERPPGPw9N5pUL8ihlJmIMYzj4Y=
    - secure: TNFYL3btw/7gwOugJkhzKYlD6GXlaC6ChNPfTIPSVqykrRY3BQKp4ob2GWRn9ttj4iJK/INksWDBf2OVPqJlXz3nuS60N5aCobASoYM0HscQCRbvAFV2rVsSFduRRXl0Li46dgeK1o5oO9fn7EoCsSFdsk4bpBP1tBf+0+BuOfN5ruQC2ecbxHAruj2jq6itcMksFiUjDLmvb8uEvIDFF22GXF1z0NZ/GUR5QpI5fssMb1GJjabqdwCCv/l0zmqFq8Xw0CBPhE9GTOtBJXzAGmuDIYSkpvBE09L5qKM4Qe9JgarVGJIWTfBc3GqaDAA5xnEKktJbDzIZ+q1BE+whKoD8CS2hTOc8ozIqg1esikLrsC1Sl2YmKhraxzvS3PIFxwDu4jbu/H6e8dzB1zbkVk3cRZQQLd5BTfxA2Jm3pRJRlVZeL4eTTDyk1GYeSr7ik41ipkLxBFIyFBMssF6KBw8nqLAXAjNLYUb50m0qiINQKJWRjcR/Qay1kWHfOFlFmfUKa9bh/PkhQr/NVYesRk+ekmckuCfBaDC1r71719UrIfDK4jdv24io6OCX5QN/KJRsaJArqv0CnCNdmaghwB3fGaPoY/bnTFkNc/IV/uebuFcyGBKL+kjRTXu0z3MGGhiQoTBAm3IOANWKdoN3SfprtuN1PVWBIgE59TDT3z8=
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO="docai/exposomics"

before_install:
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - export publicUrl=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "https://exposomics.doc.ai"; else echo https://exposomics.$TRAVIS_BRANCH.docai.co
    ; fi`
  - docker build -f Dockerfile --build-arg googleMapsApiKey=$googleMapsApiKey --build-arg publicUrl=$publicUrl -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
